# .github/workflows/publish-to-pypi.yml

name: Publish pycodetags to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.0                                     # v4.2.2
      with:
        persist-credentials: false

    - uses: actions/setup-python@v6.1.0                                     # v5.6.0
      with:
        python-version: '3.14'

    - name: Install uv and pipx
      run: |
        pip install uv && pip install pipx

    - name: Install global dependencies
      run: |
        pipx install uv && pipx install "coderoller" && \
        pipx install isort && pipx install black && pipx install bandit && \
        pipx install pylint && pipx install pre-commit && pipx install poetry && pipx install hatch

    - name: Install Dependencies
      run: uv sync

    - name: Run make check
      run: chmod +x *.sh && uv run make check

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.5.1                                     # v5.4.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run make publish
      run: uv run make publish

    - name: Upload Package
      uses: actions/upload-artifact@v5.0.0                                     # v4.6.2
      with:
        name: packages
        path: dist/
        if-no-files-found: error
        retention-days: 1

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pycodetags
    permissions:
      id-token: write
    needs: build
    steps:
    - name: Fail if branch is not main
      if: github.event_name == 'workflow_dispatch' && github.ref != 
        'refs/heads/main'
      run: |
        echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
        exit 1
    - name: Check out code
      uses: actions/checkout@v6.0.0                                     # v4.2.2
      with:
        persist-credentials: false

    - name: Download artifact
      uses: actions/download-artifact@v6.0.0                                     # v4.3.0
      with:
        name: packages
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.13.0                                    # v1.12.4
